[package]
name = "sig_v4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12"
sha2 = "0.10"
ring = "0.17"
hex = "0.4"
time = "0.3"