[package]
name = "sig_v4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ring = "0.17"
time = "0.3"
typed-builder = "0.18.0"
hmac = "0.12.1"
hex = "0.4"
sha2 = "0.10.8"